### ISSUE TITLE
add self in main.py

### ISSUE THREAD

**Issue by MarkusHackspacher** [TreeNote/TreeNote#33]
have try to start TreeNote from source with Windows7, Python 3.5 with PyQt version 5.6.
I got this fault:
```
Traceback (most recent call last):
  File "C:\...\TreeNote-master\TreeNote.py", line 9, in <module>
    treenote.main.start()
  File "C:\...\TreeNote-master\treenote\main.py", line 2564, in start
    form = MainWindow(app)
  File "C:\....\TreeNote-master\treenote\main.py", line 304, in __init__
    shct='Ctrl+,'))
  File "C:\Users\mhackspacher\Downloads\TreeNote-master\treenote\main.py", line 283, in act
    action = QAction(QIcon.fromTheme(icon_name), name)
TypeError: arguments did not match any overloaded call:
  QAction(QObject): argument 1 has unexpected type 'QIcon'
  QAction(str, QObject): argument 1 has unexpected type 'QIcon'
  QAction(QIcon, str, QObject): not enough arguments
```

I add `, self` in main.py line 283 and 285 than is runs:

```
            if icon_name:
                action = QAction(QIcon.fromTheme(icon_name), name, self)
            else:
                action = QAction(name, self)
```

**Comment by Tamriel** [comment]
Thanks! I guess it is a PyQt 5.6 issue. Since your proposed changes work with PyQt 5.7, too, I applied them.
