### ISSUE TITLE
change a case from 1-7 to 0 in plan view

### ISSUE THREAD

**Issue by MarkusHackspacher** [TreeNote/TreeNote#39]
I got this Traceback if I change a case from 1-7 to 0 in plan view. The software continues to work normally.

```
Traceback (most recent call last):
  File "C:\...\treenote\main.py", line 1524, in set_plan
    self.select(self.get_indexes_from_creation_dates(creation_dates))
  File "C:\...\treenote\main.py", line 921, in select
    view.selectionModel().setCurrentIndex(index, QItemSelectionModel.Select)
UnboundLocalError: local variable 'index' referenced before assignment
```

**Comment by Tamriel** [comment]
There are still several issues in the plan view. I like (and use) that concept, but I have a more mighty and natural alternative to it. Therefore I did not document it in the manual and would like to ditch it in favour of the alternative. However, I will have time not before september.
